"""SQLAlchemy ORM models for TimescaleDB tables."""

from datetime import datetime
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    Integer,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Base class for all SQLAlchemy models."""
    pass


class CandleModel(Base):
    """OHLCV candle data (TimescaleDB hypertable)."""

    __tablename__ = "candles"

    time: Mapped[datetime] = mapped_column(DateTime(timezone=True), primary_key=True)
    symbol: Mapped[str] = mapped_column(String(20), primary_key=True)
    timeframe: Mapped[str] = mapped_column(String(5), primary_key=True)
    exchange: Mapped[str] = mapped_column(String(20), default="binance")
    open: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    high: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    low: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    close: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    volume: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    quote_volume: Mapped[float | None] = mapped_column(Numeric(20, 8), nullable=True)
    trades_count: Mapped[int | None] = mapped_column(Integer, nullable=True)


class SignalModel(Base):
    """Trading signals generated by the system."""

    __tablename__ = "signals"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    signal_grade: Mapped[str] = mapped_column(String(1), nullable=False)
    signal_strength: Mapped[float] = mapped_column(Numeric(5, 4), nullable=False)
    entry_price: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    entry_zone_low: Mapped[float | None] = mapped_column(Numeric(20, 8))
    entry_zone_high: Mapped[float | None] = mapped_column(Numeric(20, 8))
    stop_loss: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    sl_type: Mapped[str] = mapped_column(String(20), nullable=False)
    tp1_price: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    tp1_pct: Mapped[int] = mapped_column(Integer, default=50)
    tp2_price: Mapped[float | None] = mapped_column(Numeric(20, 8))
    tp2_pct: Mapped[int | None] = mapped_column(Integer, default=30)
    tp3_price: Mapped[float | None] = mapped_column(Numeric(20, 8))
    tp3_pct: Mapped[int | None] = mapped_column(Integer, default=20)
    rr_tp1: Mapped[float | None] = mapped_column(Numeric(5, 2))
    rr_tp2: Mapped[float | None] = mapped_column(Numeric(5, 2))
    rr_tp3: Mapped[float | None] = mapped_column(Numeric(5, 2))
    weighted_rr: Mapped[float | None] = mapped_column(Numeric(5, 2))
    position_size_qty: Mapped[float | None] = mapped_column(Numeric(20, 8))
    leverage: Mapped[int] = mapped_column(Integer, default=1)
    risk_amount: Mapped[float | None] = mapped_column(Numeric(20, 8))
    strategy_scores: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    market_context: Mapped[dict | None] = mapped_column(JSONB)
    ml_confidence: Mapped[float | None] = mapped_column(Numeric(5, 4))
    status: Mapped[str] = mapped_column(String(20), default="ACTIVE")
    outcome: Mapped[str | None] = mapped_column(String(20))
    actual_pnl: Mapped[float | None] = mapped_column(Numeric(20, 8))


class OrderModel(Base):
    """Executed orders."""

    __tablename__ = "orders"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )
    signal_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False))
    exchange_order_id: Mapped[str | None] = mapped_column(String(50))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    side: Mapped[str] = mapped_column(String(10), nullable=False)
    order_type: Mapped[str] = mapped_column(String(20), nullable=False)
    price: Mapped[float | None] = mapped_column(Numeric(20, 8))
    quantity: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    filled_qty: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    avg_fill_price: Mapped[float | None] = mapped_column(Numeric(20, 8))
    status: Mapped[str] = mapped_column(String(20), default="PENDING")
    fees: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    metadata_json: Mapped[dict | None] = mapped_column(JSONB)


class PositionModel(Base):
    """Active and historical positions."""

    __tablename__ = "positions"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )
    signal_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False))
    opened_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    entry_price: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    current_price: Mapped[float | None] = mapped_column(Numeric(20, 8))
    quantity: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    remaining_qty: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    leverage: Mapped[int] = mapped_column(Integer, default=1)
    stop_loss: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    tp1_price: Mapped[float | None] = mapped_column(Numeric(20, 8))
    tp2_price: Mapped[float | None] = mapped_column(Numeric(20, 8))
    tp3_price: Mapped[float | None] = mapped_column(Numeric(20, 8))
    unrealized_pnl: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    realized_pnl: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    total_fees: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    status: Mapped[str] = mapped_column(String(20), default="OPEN")
    close_reason: Mapped[str | None] = mapped_column(String(30))
    trading_mode: Mapped[str] = mapped_column(String(10), server_default="paper")  # "paper" or "live"
    exchange_order_id: Mapped[str | None] = mapped_column(String(100))
    strategy_name: Mapped[str | None] = mapped_column(String(50))
    dca_data_json: Mapped[dict | None] = mapped_column(JSONB)
    metadata_json: Mapped[dict | None] = mapped_column(JSONB)


class BacktestRunModel(Base):
    """Backtest run results."""

    __tablename__ = "backtest_runs"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid4())
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    strategy_name: Mapped[str] = mapped_column(String(50), nullable=False)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(5), nullable=False)
    start_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    end_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    initial_capital: Mapped[float] = mapped_column(Numeric(20, 8), nullable=False)
    final_capital: Mapped[float | None] = mapped_column(Numeric(20, 8))
    total_return: Mapped[float | None] = mapped_column(Numeric(10, 4))
    sharpe_ratio: Mapped[float | None] = mapped_column(Numeric(8, 4))
    sortino_ratio: Mapped[float | None] = mapped_column(Numeric(8, 4))
    max_drawdown: Mapped[float | None] = mapped_column(Numeric(8, 4))
    win_rate: Mapped[float | None] = mapped_column(Numeric(5, 4))
    profit_factor: Mapped[float | None] = mapped_column(Numeric(8, 4))
    total_trades: Mapped[int | None] = mapped_column(Integer)
    parameters: Mapped[dict | None] = mapped_column(JSONB)
    equity_curve: Mapped[dict | None] = mapped_column(JSONB)
    trades: Mapped[dict | None] = mapped_column(JSONB)
    status: Mapped[str] = mapped_column(String(20), default="QUEUED", server_default="QUEUED")
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    annual_return: Mapped[float | None] = mapped_column(Numeric(10, 4))
    expectancy: Mapped[float | None] = mapped_column(Numeric(10, 4))
    avg_win: Mapped[float | None] = mapped_column(Numeric(20, 8))
    avg_loss: Mapped[float | None] = mapped_column(Numeric(20, 8))
    calmar_ratio: Mapped[float | None] = mapped_column(Numeric(10, 4))
    avg_holding_period: Mapped[float | None] = mapped_column(Numeric(10, 2))


class UserModel(Base):
    """Application user accounts."""

    __tablename__ = "users"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid4())
    )
    username: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class UserSettingsModel(Base):
    """User settings including encrypted exchange keys."""

    __tablename__ = "user_settings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    exchange_keys_encrypted: Mapped[bytes | None] = mapped_column(nullable=True)
    risk_params: Mapped[dict] = mapped_column(JSONB, default=dict)
    strategy_config: Mapped[dict] = mapped_column(JSONB, default=dict)
    notification_config: Mapped[dict] = mapped_column(JSONB, default=dict)
    signal_policy: Mapped[dict] = mapped_column(JSONB, default=dict)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class BotStateModel(Base):
    """Auto-bot state persistence."""

    __tablename__ = "bot_state"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    is_running: Mapped[bool] = mapped_column(Boolean, default=False)
    is_paper_mode: Mapped[bool] = mapped_column(Boolean, default=True)
    active_strategies: Mapped[list] = mapped_column(JSONB, default=list)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    stopped_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    total_pnl: Mapped[float] = mapped_column(Numeric(20, 8), default=0)
    paper_balance: Mapped[float | None] = mapped_column(Numeric(20, 8))
    paper_initial_balance: Mapped[float | None] = mapped_column(Numeric(20, 8))
    metadata_json: Mapped[dict] = mapped_column(JSONB, default=dict)
